MafiaCasinoWeb/Controllers/CasinoController.cs
using AutoMapper;
using BusinessLogic.Services;
using Casino;
using DAL;
using DAL.Models;
using DAL.Models.VM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;

namespace MafiaCasinoWeb.Controllers
{
    [Authorize]
    public class CasinoController : Controller
    {
        private readonly UserService _userService;

        public CasinoController(UserService userService)
        {
            _userService = userService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Riches()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<User, UserVM>());
            var mapper = config.CreateMapper();

            List<UserVM> mappedUsers = await _userService.GetRichesAsync(10);
            return View(mappedUsers);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Slots()
        {
            return View(SlotsList.GetAllSlots());
        }

        public async Task<IActionResult> HatSlot()
        {
            return View();
        }
    }
}

MafiaCasinoWeb/Controllers/HomeController.cs
using BusinessLogic.Services;
using DAL.Models;
using DAL.Models.VM;
using DAL.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MafiaCasinoWeb.Controllers
{
    [Authorize]
    public class HomeController : Controller
	{
        private readonly UserService _userService;

        public HomeController(UserService userService)
        {
            _userService = userService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
		public IActionResult SignIn(string ReturnUrl)
		{
			var user = HttpContext.User.Identity.IsAuthenticated;
			if (user)
			{
				return RedirectToAction("Index");
			}
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> SignIn(LoginUserVM model, string ReturnUrl)
        {
            var valdator = new LoginUserValidation();
            var validationresult = await valdator.ValidateAsync(model);
            if (validationresult.IsValid)
            {
                var result = await _userService.LoginUserAsync(model);
                if (result.Success)
                {
                    if(ReturnUrl == null)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    return Redirect(ReturnUrl);
                }
                ViewBag.AuthError = result.Message;
                return View(model);
            }
            return View(model);
        }

        [AllowAnonymous]
        public IActionResult SignUp()
        {
            var user = HttpContext.User.Identity.IsAuthenticated;
            if (user)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> SignUp(RegisterUserVM model)
        {
            //var validator = new RegisterUserValidation();
            //var validationresult = await validator.ValidateAsync(model);
            //if (validationresult.IsValid)
            //{
            //    var result = await _userService.RegisterUserAsync(model);
            //    if (result.Success)
            //    {
            //        return RedirectToAction("SignIn", "Admin");
            //    }

            //    ViewBag.AuthError = result.Message;
            //    return View(model);
            //}
            //ViewBag.AuthError = validationresult.Errors.First();
            //return View(model);

            var result = await _userService.RegisterUserAsync(model);
            if (result.Success)
            {
                return RedirectToAction(nameof(SignIn));
            }

            ViewBag.AuthError = result.Message;
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            var result = await _userService.LogoutUserAsync();
            if (result.Success)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Admin");
        }


		public async Task<IActionResult> Profile()
		{

			var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
			var result = await _userService.GetUserProfileAsync(userId);
			if (result.Success)
			{
				return View(result.Payload);
			}
			return RedirectToAction("Index", "Home");
		}
	}
}

MafiaCasinoWeb/Views/Casino/HatSlot.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MafiaCasinoWeb/Views/Casino/Riches.cshtml
@using DAL.Models.VM;
@using Microsoft.AspNetCore.Identity
@using DAL.Models;
@using DAL;
@model List<UserVM>

<div class="text-center">
	<h1 class="display-4">The rich mans</h1>
	<div>
        <table>
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Cash</th>
                    <th>Highest Bet</th>
                    <th>Highest Win</th>
                    <th>Total Bets Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>@user.Cash</td>
                        <td>@user.HighestBet</td>
                        <td>@user.HighestWin</td>
                        <td>@user.TotalBetsCount</td>
                    </tr>
                }
            </tbody>
        </table>
	</div>
</div>

MafiaCasinoWeb/Views/Casino/Slots.cshtml
@using Casino
@using Microsoft.AspNetCore.Mvc.TagHelpers;
@using global::Casino;

@model List<SlotPreview>
@{
    ViewData["Title"] = "Slots";
}
<div class="text-center">
    <h1 class="display-4">Slots</h1>
</div>
<div style="display: flex; justify-content: space-around;">
    <div class="slots">
        @foreach (var slot in Model)
        {
            <div class="slot-container">
                <div onclick="javascript:RidirectDivClick('@slot.Action');" class="slot-prev" style="background-image: url('@slot.Image');">
                    <p class="slot-name">@slot.Name</p>
                    <div style="display: none;">@slot.PrevImage</div>
                    <div style="display: none;">@slot.Description</div>
                </div>
            </div>
        }
    </div>
    <div class="slot-info">
        <h2 class="slot-name-prev"></h2>
        <img class="slot-screen"/>
        <div id="slot-desc"></div>
    </div>
</div>
<script>

const slotDesc = document.getElementById('slot-desc');
const slotName = document.getElementsByClassName('slot-name-prev')[0];
const slotScreen = document.getElementsByClassName("slot-screen")[0];
const slotPrevs = document.getElementsByClassName("slot-prev");

for (let i = 0; i < slotPrevs.length; i++) {
    slotPrevs[i].addEventListener('mouseover', function(){ShowInfo(slotPrevs[i].children[0].textContent, slotPrevs[i].children[1].textContent, slotPrevs[i].children[2].textContent)});
}

// Add a "mouseover" event listener
//myDiv.addEventListener('mouseover', );

function ShowInfo(name, image, info){
    slotName.textContent = name;
    slotScreen.setAttribute("src", `${image}`);
    slotDesc.innerHTML = info;
}

function RidirectDivClick(action)
{
    window.location.href = '/casino/' + action;
}

</script>

MafiaCasinoWeb/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MafiaCasinoWeb/Views/Home/Profile.cshtml
@using DAL.Models.VM;
@model UserProfileVM

<section>
	<div class="text-center">
		<h1 class="display-4" style="text-shadow: 3px 3px 1px rgba(0,0,0,0.5); font-weight:400;">Profile</h1>
	</div>
	<link rel="stylesheet" href="~/css/profile.css" asp-append-version="true"/>
	<div class="user-profile">
		<div class="name-container">
			<img class="user-avatar" src="@Model.Avatar"/>
			<h3 class="display-6 user-name">@Model.UserName</h3>
		</div>
		<h5>Cash: @Model.Cash</h5>
		@Html.Partial("_RewardsPartial", Model.Rewards)
	</div>
</section>

MafiaCasinoWeb/Views/Home/SignIn.cshtml
@using DAL.Models.VM;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@model LoginUserVM

<section>
    <div class="page-header min-vh-75">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
                    <div class="card card-plain mt-8">
                        <div class="card-header pb-0 text-left bg-transparent">
                            <h3 class="font-weight-bolder text-info text-gradient">Welcome back</h3>
                            <p class="mb-0">Enter your email and password to sign in</p>
                        </div>
                        <div class="card-body">
                            @if (@ViewBag.AuthError != null)
                            {
                                    <span class="text-danger">@ViewBag.AuthError</span>
                            }
                            <form role="form" asp-controller="Home" asp-action="SignIn" asp-route-returnUrl="@Context.Request.Query["ReturnUrl"]" method="post">
                                <label>Email</label>
                                <div class="mb-3">
                                    <input type="email" asp-for="Email" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="email-addon">
                                    <span class="text-danger" asp-validation-for="Email"></span>
                                </div>
                                <label>Password</label>
                                <div class="mb-3">
                                    <input type="password" asp-for="Password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="password-addon">
                                    <span class="text-danger" asp-validation-for="Password"></span>
                                </div>
                                <div class="form-check form-switch">
                                    <input class="form-check-input" asp-for="RememberMe" type="checkbox" id="rememberMe" checked="">
                                    <label class="form-check-label" for="rememberMe">Remember me</label>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Sign in</button>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center pt-0 px-lg-2 px-1">
                            <p class="mb-4 text-sm mx-auto">
                                Don't have an account?
                                <a asp-action="SignUp" asp-controller="Home" class="text-info text-gradient font-weight-bold">Sign up</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                        <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url('../assets/img/curved-images/curved6.jpg')"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

MafiaCasinoWeb/Views/Home/SignUp.cshtml
@using DAL.Models.VM;
@model RegisterUserVM
<section class="min-vh-100 mb-8">
    <div class="page-header align-items-start min-vh-50 pt-5 pb-11 m-3 border-radius-lg" style="background-image: url('../assets/img/curved-images/curved14.jpg');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5 text-center mx-auto">
                    <h1 class="text-white mb-2 mt-5">Welcome!</h1>
                    <p class="text-lead text-white">Use these awesome forms to login or create new account in your project for free.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row mt-lg-n10 mt-md-n11 mt-n10">
            <div class="col-xl-4 col-lg-5 col-md-7 mx-auto">
                <div class="card z-index-0">
                    <div class="card-header text-center pt-4">
                        <h5>Register with</h5>
                    </div>
                    <div class="row px-xl-5 px-sm-4 px-3">
                        <div class="col-12 me-auto px-1">
                            <a class="btn btn-outline-light w-100" href="javascript:;">
                                <svg width="24px" height="32px" viewBox="0 0 64 64" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                                    <g id="Artboard" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <g id="google-icon" transform="translate(3.000000, 2.000000)" fill-rule="nonzero">
                                            <path d="M57.8123233,30.1515267 C57.8123233,27.7263183 57.6155321,25.9565533 57.1896408,24.1212666 L29.4960833,24.1212666 L29.4960833,35.0674653 L45.7515771,35.0674653 C45.4239683,37.7877475 43.6542033,41.8844383 39.7213169,44.6372555 L39.6661883,45.0037254 L48.4223791,51.7870338 L49.0290201,51.8475849 C54.6004021,46.7020943 57.8123233,39.1313952 57.8123233,30.1515267" id="Path" fill="#4285F4"></path>
                                            <path d="M29.4960833,58.9921667 C37.4599129,58.9921667 44.1456164,56.3701671 49.0290201,51.8475849 L39.7213169,44.6372555 C37.2305867,46.3742596 33.887622,47.5868638 29.4960833,47.5868638 C21.6960582,47.5868638 15.0758763,42.4415991 12.7159637,35.3297782 L12.3700541,35.3591501 L3.26524241,42.4054492 L3.14617358,42.736447 C7.9965904,52.3717589 17.959737,58.9921667 29.4960833,58.9921667" id="Path" fill="#34A853"></path>
                                            <path d="M12.7159637,35.3297782 C12.0932812,33.4944915 11.7329116,31.5279353 11.7329116,29.4960833 C11.7329116,27.4640054 12.0932812,25.4976752 12.6832029,23.6623884 L12.6667095,23.2715173 L3.44779955,16.1120237 L3.14617358,16.2554937 C1.14708246,20.2539019 0,24.7439491 0,29.4960833 C0,34.2482175 1.14708246,38.7380388 3.14617358,42.736447 L12.7159637,35.3297782" id="Path" fill="#FBBC05"></path>
                                            <path d="M29.4960833,11.4050769 C35.0347044,11.4050769 38.7707997,13.7975244 40.9011602,15.7968415 L49.2255853,7.66898166 C44.1130815,2.91684746 37.4599129,0 29.4960833,0 C17.959737,0 7.9965904,6.62018183 3.14617358,16.2554937 L12.6832029,23.6623884 C15.0758763,16.5505675 21.6960582,11.4050769 29.4960833,11.4050769" id="Path" fill="#EB4335"></path>
                                        </g>
                                    </g>
                                </svg>
                            </a>
                        </div>
                        <div class="mt-2 position-relative text-center">
                            <p class="text-sm font-weight-bold mb-2 text-secondary text-border d-inline z-index-2 bg-white px-3">
                                or
                            </p>
                        </div>
                    </div>
                    <div class="card-body">
                        <form role="form text-left" method="post" asp-controller="Home" asp-action="SignUp">
                            @if (@ViewBag.AuthError != null)
                            {
                                <span class="text-danger">@ViewBag.AuthError</span>
                            }
                            <div class="mb-3">
                                <input asp-for="UserName" type="text" class="form-control" placeholder="UserName" aria-label="UserName" aria-describedby="email-addon">
                                <span class="text-danger" asp-validation-for="UserName"></span>
                            </div>
                            <div class="mb-3">
                                <input asp-for="Email" type="email" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="email-addon">
                                <span class="text-danger" asp-validation-for="Email"></span>
                            </div>
                            <div class="mb-3">
                                <input asp-for="Password" type="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="password-addon">
                                <span class="text-danger" asp-validation-for="Password"></span>
                            </div>

                            <div class="mb-3">
                                <input asp-for="ConfirmPassword" type="password" class="form-control" placeholder="Confirm Password" aria-label="Confirm Password" aria-describedby="password-addon">
                                <span class="text-danger" asp-validation-for="ConfirmPassword"></span>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn bg-gradient-dark w-100 my-4 mb-2">Sign up</button>
                            </div>
                            <p class="text-sm mt-3 mb-0">Already have an account? <a asp-controller="Home" asp-action="SignIn" class="text-dark font-weight-bolder">Sign in</a></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MafiaCasinoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mafia Casino - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MafiaCasinoWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Mafia Casino</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Casino" asp-action="Slots">Slots</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Casino" asp-action="Riches">Wealthy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Creators">Creators</a>
                        </li>
                        <partial name="_LoginPartial" /> 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div style="padding:10px;">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MafiaCasinoWeb - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MafiaCasinoWeb/Views/Shared/_RewardsPartial.cshtml
@using DAL.Models.VM;
@model List<RewardsVM>

<div>
	<link rel="stylesheet" href="~/css/rewards.css"/>
	<div class="text-center">
		<h4>Rewards:</h4>
	</div>

	<div class="reward-list">
		@foreach (var reward in Model)
		{
			@*<button type="button" style="display: inline" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" 
			data-bs-content="<div>@reward.Description</div><p>@reward.Progress/@reward.Target</p>"
			data-bs-original-title="@reward.Name">@reward.Name</button>*@
			<div class="@(reward.Progress >= reward.Target ? "reward collected" : "reward")">
				<h5>@reward.Name</h5>
				<p>@reward.Description</p>
				<p class="reward-progress">@reward.Progress/@reward.Target</p>
			</div>
		}
	</div>
</div>